var ext = {
  plusIconLink: "",
  eraseIconLink: "",
  closeIconLink: "",
  moveUpIconLink: "",
  moveDownIconLink: "",

  supportedURLsPattern:
    "^https?://[^/]+/i/(?:subscription|collection/content/user)/.*$",
  defaultUrlPrefixPattern: "https?://[^/]+/i/",
  subscriptionUrlPrefixPattern: "https?://[^/]+/i/feed/content",
  categoryUrlPrefixPattern: "https?://[^/]+/i/collection/content/user/[^/]+/",

  settingsBtnPredecessorSelector: ".header .MarkAsReadButton",
  articlesContainerSelector: ".list-entries",
  articlesChunkClass: "EntryList__chunk",
  articlesChunkSelector: ".EntryList__chunk",
  articleSelector:
    ".EntryList__chunk > :where(article, .InlineArticle--u100):not([gap-article])",
  articleAndGapSelector:
    ".EntryList__chunk > :where(article, .InlineArticle--u100)",
  articleIdSelector: ".EntryList__chunk article[id]",
  articleIdFromFrameSelector: "article[id]",
  sortedArticlesSelector: ".EntryList__chunk article[id]:not([gap-article])",
  articleAndInlineSelector:
    ".EntryList__chunk > :where(article, .InlineArticle):not([gap-article])",
  inlineArticleFrameSelector: ".InlineArticle",
  readArticleSelector: "article[id].entry--read",
  unreadArticleSelector: "article[id].entry--unread",
  unreadArticlesCountSelector:
    ".entry--unread:not([gap-article]), .Article__title:not(.Article__title--read)",
  uncheckedArticlesSelector: ":not([gap-article]):not([checked-FFnS])",
  checkedArticlesAttribute: "checked-FFnS",
  markAsReadImmediatelySelector: ".list-entries .FFnS-mark-as-read",
  unreadArticleClass: "entry--unread",
  readArticleClass: "entry--read",
  articleTitleSelector: ".EntryTitle,.Article__title",
  articleViewUrlAnchorSelector: ".Article__title",
  articleVisualSelector: ".EntryVisual",
  inlineViewClass: "InlineArticle",
  articleViewReadTitleClass: "Article__title--read",
  articleViewReadSelector: ".Article__title--read",
  articleViewEntryContainerSelector: ".u100",
  loadingMessageSelector: ".list-entries .EntryList__loading",
  sectionSelector: "#timeline > .section",
  publishAgeSpanSelector: ".ago, .metadata [title^=published]",
  publishAgeTimestampAttr: "title",
  articleSourceSelector: ".entry__source",
  subscriptionChangeSelector: "#header-title",
  popularitySelector: ".EntryEngagement, .engagement, .nbrRecommendations",
  hidingInfoSibling: "header .right-col, header > h1 .button-dropdown",

  keepArticlesUnreadId: "keepArticlesUnread",
  articlesToMarkAsReadId: "articlesToMarkAsRead",
  openAndMarkAsReadId: "isOpenAndMarkAsRead",
  openAndMarkAsReadClass: "open-in-new-tab-button",
  visualOpenAndMarkAsReadId: "isVisualOpenAndMarkAsRead",
  titleOpenAndMarkAsReadId: "isTitleOpenAndMarkAsRead",
  markAsReadAboveBelowId: "isMarkAsReadAboveBelowId",
  markAsReadAboveBelowClass: "mark-as-read-above-below-button",
  entryInfosJsonClass: "entryInfosJson",
  hideWhenMarkAboveBelowId: "isHideWhenMarkAboveBelow",
  hideAfterReadId: "isHideAfterRead",
  autoLoadAllArticlesId: "autoLoadAllArticles",
  batchSizeId: "batchSize",
  loadByBatchEnabledId: "loadByBatchEnabled",
  isNewestFirstId: "isNewestFirst",
  markAsReadAboveBelowReadId: "MarkAsReadAboveBelowRead",
  markAsReadImmediatelyClass: "FFnS-mark-as-read",
  buttonsContainerId: "FFnS-buttons-container",
  containerButtonClass: "FFnS-UI-button",
  openCurrentFeedArticlesId: "isOpenCurrentFeedArticles",
  openCurrentFeedArticlesClass: "open-current-articles-in-new-tab-button",
  disableAllFiltersButtonId: "isDisableAllFiltersButton",
  disableAllFiltersEnabled: "isDisableAllFiltersEnabled",
  disableAllFiltersButtonClass: "disable-all-filters-button",
  openCurrentFeedArticlesUnreadOnlyId: "openCurrentFeedArticlesUnreadOnly",
  markAsReadOnOpenCurrentFeedArticlesId:
    "isMarkAsReadOnOpenCurrentFeedArticles",
  maxOpenCurrentFeedArticlesId: "maxOpenCurrentFeedArticles",
  forceRefreshArticlesId: "forceRefreshArticles",
  disablePageOverridesId: "disablePageOverrides",
  articleSorterConfigId: "articleSorterConfig",
  navigatingToNextId: "navigatingToNext",
  navigatingEntry: "navigatingEntry",
  layoutChangeSelector: "input[id^='layout-']",
  loadingElementSelector: ".FFnS-loading",
};
